wget -P data/source/text -O 0.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/0.json
wget -P data/source/text -O 1.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/1.json
wget -P data/source/text -O 2.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/2.json
wget -P data/source/text -O 3.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/3.json
wget -P data/source/text -O 4.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/4.json
wget -P data/source/text -O 5.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/5.json
wget -P data/source/text -O 6.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/6.json
wget -P data/source/text -O 7.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/7.json
wget -P data/source/text -O 8.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/8.json
wget -P data/source/text -O 9.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/9.json
wget -P data/source/text -O 10.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/10.json
wget -P data/source/text -O 11.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/11.json
wget -P data/source/text -O 12.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/12.json
wget -P data/source/text -O 13.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/13.json
wget -P data/source/text -O 14.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/14.json
wget -P data/source/text -O 15.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/15.json
wget -P data/source/text -O 16.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/16.json
wget -P data/source/text -O 17.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/17.json
wget -P data/source/text -O 18.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/18.json
wget -P data/source/text -O 19.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/19.json
wget -P data/source/text -O 20.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/20.json
wget -P data/source/text -O 21.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/21.json
wget -P data/source/text -O 22.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/22.json
wget -P data/source/text -O 23.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/23.json
wget -P data/source/text -O 24.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/24.json
wget -P data/source/text -O 25.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/25.json
wget -P data/source/text -O 26.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/26.json
wget -P data/source/text -O 27.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/27.json
wget -P data/source/text -O 28.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/28.json
wget -P data/source/text -O 29.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/29.json
wget -P data/source/text -O 30.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/30.json
wget -P data/source/text -O 31.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/31.json
wget -P data/source/text -O 32.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/32.json
wget -P data/source/text -O 33.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/33.json
wget -P data/source/text -O 34.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/34.json
wget -P data/source/text -O 35.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/35.json
wget -P data/source/text -O 36.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/36.json
wget -P data/source/text -O 37.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/37.json
wget -P data/source/text -O 38.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/38.json
wget -P data/source/text -O 39.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/39.json
wget -P data/source/text -O 40.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/40.json
wget -P data/source/text -O 41.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/41.json
wget -P data/source/text -O 42.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/42.json
wget -P data/source/text -O 43.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/43.json
wget -P data/source/text -O 44.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/44.json
wget -P data/source/text -O 45.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/45.json
wget -P data/source/text -O 46.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/46.json
wget -P data/source/text -O 47.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/47.json
wget -P data/source/text -O 48.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/48.json
wget -P data/source/text -O 49.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/49.json
wget -P data/source/text -O 50.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/50.json
wget -P data/source/text -O 51.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/51.json
wget -P data/source/text -O 52.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/52.json
wget -P data/source/text -O 53.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/53.json
wget -P data/source/text -O 54.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/54.json
wget -P data/source/text -O 55.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/55.json
wget -P data/source/text -O 56.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/56.json
wget -P data/source/text -O 57.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/57.json
wget -P data/source/text -O 58.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/58.json
wget -P data/source/text -O 59.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/59.json
wget -P data/source/text -O 60.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/60.json
wget -P data/source/text -O 61.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/61.json
wget -P data/source/text -O 62.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/62.json
wget -P data/source/text -O 63.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/63.json
wget -P data/source/text -O 64.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/64.json
wget -P data/source/text -O 65.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/65.json
wget -P data/source/text -O 66.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/66.json
wget -P data/source/text -O 67.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/67.json
wget -P data/source/text -O 68.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/68.json
wget -P data/source/text -O 69.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/69.json
wget -P data/source/text -O 70.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/70.json
wget -P data/source/text -O 71.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/71.json
wget -P data/source/text -O 72.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/72.json
wget -P data/source/text -O 73.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/73.json
wget -P data/source/text -O 74.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/74.json
wget -P data/source/text -O 75.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/75.json
wget -P data/source/text -O 76.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/76.json
wget -P data/source/text -O 77.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/77.json
wget -P data/source/text -O 78.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/78.json
wget -P data/source/text -O 79.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/79.json
wget -P data/source/text -O 80.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/80.json
wget -P data/source/text -O 81.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/81.json
wget -P data/source/text -O 82.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/82.json
wget -P data/source/text -O 83.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/83.json
wget -P data/source/text -O 84.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/84.json
wget -P data/source/text -O 85.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/85.json
wget -P data/source/text -O 86.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/86.json
wget -P data/source/text -O 87.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/87.json
wget -P data/source/text -O 88.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/88.json
wget -P data/source/text -O 89.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/89.json
wget -P data/source/text -O 90.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/90.json
wget -P data/source/text -O 91.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/91.json
wget -P data/source/text -O 92.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/92.json
wget -P data/source/text -O 93.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/93.json
wget -P data/source/text -O 94.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/94.json
wget -P data/source/text -O 95.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data/95.json