wget -P data/source/embedding/0.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/0.json
wget -P data/source/embedding/1.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/1.json
wget -P data/source/embedding/2.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/2.json
wget -P data/source/embedding/3.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/3.json
wget -P data/source/embedding/4.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/4.json
wget -P data/source/embedding/5.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/5.json
wget -P data/source/embedding/6.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/6.json
wget -P data/source/embedding/7.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/7.json
wget -P data/source/embedding/8.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/8.json
wget -P data/source/embedding/9.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/9.json
wget -P data/source/embedding/10.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/10.json
wget -P data/source/embedding/11.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/11.json
wget -P data/source/embedding/12.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/12.json
wget -P data/source/embedding/13.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/13.json
wget -P data/source/embedding/14.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/14.json
wget -P data/source/embedding/15.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/15.json
wget -P data/source/embedding/16.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/16.json
wget -P data/source/embedding/17.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/17.json
wget -P data/source/embedding/18.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/18.json
wget -P data/source/embedding/19.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/19.json
wget -P data/source/embedding/20.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/20.json
wget -P data/source/embedding/21.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/21.json
wget -P data/source/embedding/22.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/22.json
wget -P data/source/embedding/23.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/23.json
wget -P data/source/embedding/24.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/24.json
wget -P data/source/embedding/25.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/25.json
wget -P data/source/embedding/26.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/26.json
wget -P data/source/embedding/27.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/27.json
wget -P data/source/embedding/28.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/28.json
wget -P data/source/embedding/29.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/29.json
wget -P data/source/embedding/30.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/30.json
wget -P data/source/embedding/31.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/31.json
wget -P data/source/embedding/32.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/32.json
wget -P data/source/embedding/33.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/33.json
wget -P data/source/embedding/34.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/34.json
wget -P data/source/embedding/35.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/35.json
wget -P data/source/embedding/36.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/36.json
wget -P data/source/embedding/37.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/37.json
wget -P data/source/embedding/38.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/38.json
wget -P data/source/embedding/39.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/39.json
wget -P data/source/embedding/40.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/40.json
wget -P data/source/embedding/41.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/41.json
wget -P data/source/embedding/42.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/42.json
wget -P data/source/embedding/43.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/43.json
wget -P data/source/embedding/44.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/44.json
wget -P data/source/embedding/45.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/45.json
wget -P data/source/embedding/46.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/46.json
wget -P data/source/embedding/47.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/47.json
wget -P data/source/embedding/48.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/48.json
wget -P data/source/embedding/49.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/49.json
wget -P data/source/embedding/50.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/50.json
wget -P data/source/embedding/51.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/51.json
wget -P data/source/embedding/52.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/52.json
wget -P data/source/embedding/53.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/53.json
wget -P data/source/embedding/54.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/54.json
wget -P data/source/embedding/55.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/55.json
wget -P data/source/embedding/56.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/56.json
wget -P data/source/embedding/57.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/57.json
wget -P data/source/embedding/58.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/58.json
wget -P data/source/embedding/59.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/59.json
wget -P data/source/embedding/60.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/60.json
wget -P data/source/embedding/61.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/61.json
wget -P data/source/embedding/62.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/62.json
wget -P data/source/embedding/63.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/63.json
wget -P data/source/embedding/64.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/64.json
wget -P data/source/embedding/65.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/65.json
wget -P data/source/embedding/66.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/66.json
wget -P data/source/embedding/67.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/67.json
wget -P data/source/embedding/68.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/68.json
wget -P data/source/embedding/69.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/69.json
wget -P data/source/embedding/70.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/70.json
wget -P data/source/embedding/71.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/71.json
wget -P data/source/embedding/72.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/72.json
wget -P data/source/embedding/73.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/73.json
wget -P data/source/embedding/74.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/74.json
wget -P data/source/embedding/75.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/75.json
wget -P data/source/embedding/76.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/76.json
wget -P data/source/embedding/77.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/77.json
wget -P data/source/embedding/78.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/78.json
wget -P data/source/embedding/79.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/79.json
wget -P data/source/embedding/80.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/80.json
wget -P data/source/embedding/81.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/81.json
wget -P data/source/embedding/82.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/82.json
wget -P data/source/embedding/83.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/83.json
wget -P data/source/embedding/84.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/84.json
wget -P data/source/embedding/85.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/85.json
wget -P data/source/embedding/86.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/86.json
wget -P data/source/embedding/87.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/87.json
wget -P data/source/embedding/88.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/88.json
wget -P data/source/embedding/89.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/89.json
wget -P data/source/embedding/90.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/90.json
wget -P data/source/embedding/91.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/91.json
wget -P data/source/embedding/92.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/92.json
wget -P data/source/embedding/93.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/93.json
wget -P data/source/embedding/94.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/94.json
wget -P data/source/embedding/95.json https://hf-mirror.com/datasets/Sirius518/NovelSum/resolve/main/all_data_embedding/95.json